export default {
  label: "צור קשר",
  title_plain: "נשמח",
  title_em: "לעזור.",
  lede: "השאירו פרטים ונחזור אליכם בתוך יום עסקים. לפניות דחופות — ישירות בטלפון או בוואטסאפ.",
  name_label: "שם מלא",
  name_placeholder: "כיצד לפנות אליך?",
  phone_label: "טלפון",
  phone_placeholder: "050-000-0000",
  email_label: "דוא״ל",
  email_placeholder: "name@example.com",
  message_label: "במה נוכל לעזור?",
  message_placeholder: "ספרו לנו על העניין המשפטי. כל המידע נשמר בדיסקרטיות מלאה.",
  submit: "שליחת הפנייה ←",
  success_msg: "תודה! פנייתך נשלחה. נחזור אליך בתוך יום עסקים.",
  error_msg: "נא למלא שם, טלפון והודעה.",
  office_phone_label: "טלפון משרד",
  office_phone: "055-956-9556",
  mobile_label: "נייד",
  mobile: "054-441-5549",
  email_label2: "אימייל",
  email: "Yaara@yl-law.net",
  address_label: "כתובת המשרד",
  address: "שד׳ הרכס 13, בניין A, קומה 4, מודיעין",
  hours_label: "שעות פעילות",
  hours: "ימים א׳–ה׳ · 09:00–18:00",
  map_title: "משרד YL — מודיעין",
  map_address: "שד׳ הרכס 13",
}
